### ISSUE TITLE
Brew install namespace

### ISSUE THREAD

**Issue by morrieinmaas** [animo/siera#235]
Currently one has to

```
brew tap animo/siera
brew install animo/siera/siera
```

suggested change:

```
brew tap animo/siera
brew install animo/siera
```
or 
```
brew tap animo/siera
brew install siera
```

Actually not sure how this works under the hood and whether that's possible at all. Small things but `animo/siera/siera` certainly slightly annoys me

**Comment by morrieinmaas** [comment]
according to the [brew docs](https://docs.brew.sh/Taps) it is what it is. still slightly puzzled as to why it is not animo/siera instead of animo/siera/siera. but there doesn't seem to be a way to change this

**Comment by blu3beri** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/61358536/197500330-6282fd52-8d49-4b55-ba80-bd1adab0450d.png">

It happens when you have two taps providing a lib/bin with the same name.

`brew untap animo/agent-cli` will fix it.

**Comment by morrieinmaas** [comment]
ohhh I see!
Thx
